import "../styles/pages/home.scss";

export function HomePage() {
    return <div class="home">
        <div class="home--video">
            <video src="/src/assets/videos/funny.mp4" autoplay={true} loop={true} muted={true}></video>
        </div>
        <div class="home--contents">
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
            hi lol<br/>
        </div>
    </div>;
}